version: '3'

services:

  # PHP Service
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - app-files:/var/www
      # - ./storage:/var/www/storage
    networks:
      - app-network

  # MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - app-files:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

volumes:
  app-files:

networks:
  app-network:
    driver: bridge
